services:
  web:
    image: carmelo0x99/goweb:multi
    ports:
      - target: 8888
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
#      replicas: 6
      placement:
        constraints:
          - node.role == worker
    networks:
      - goweb_backend

networks:
  goweb_frontend:
  goweb_backend:
    external: true
