services:
  http:
    image: carmelo0x99/goweb:1.0
    ports:
      - target: 8888
        published: 8080
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    networks:
      - backend

networks:
  frontend:
  backend:
