FROM arm32v7/golang:alpine AS builder
RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN go build -o main.go .

FROM arm32v7/alpine
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/main.go ./
CMD ["./main.go"]
