FROM arm32v6/golang:alpine AS builder
RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN go build -o goweb.go .

FROM arm32v6/alpine
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/goweb.go ./
CMD ["./goweb.go"]
